
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 31 20:54:36 ART 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXPO_1 = 3;
  public static final int IGUALIGUAL = 9;
  public static final int MULTIPLICACION = 6;
  public static final int MENOR = 10;
  public static final int ELSE = 24;
  public static final int INT = 25;
  public static final int PARENT_IZQ = 19;
  public static final int WHILE = 27;
  public static final int DIVISION = 8;
  public static final int SUMA = 5;
  public static final int PARENT_DER = 20;
  public static final int MAYIGUAL = 13;
  public static final int RETURN = 26;
  public static final int IF = 23;
  public static final int ID = 30;
  public static final int NUM = 31;
  public static final int COMA = 22;
  public static final int MENIGUAL = 11;
  public static final int DISTINTO = 14;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int CORCH_IZQ = 17;
  public static final int LLAVE_IZQ = 15;
  public static final int PUNTOCOMA = 21;
  public static final int CORCH_DER = 18;
  public static final int LLAVE_DER = 16;
  public static final int FOR = 28;
  public static final int VOID = 29;
  public static final int RESTA = 7;
  public static final int EXPO_2 = 4;
}

